In [2]:
abs(-4.6)

4.6

In [5]:
all([1,2,3,0])

False

In [8]:
any([1,2,0,0])

True

In [9]:
dir(int)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [11]:
divmod(20,3)

(6, 2)

In [17]:
#enumerate
l=[1,2,3,4,5]
for t in enumerate(l,5):
    print(t)


(5, 1)
(6, 2)
(7, 3)
(8, 4)
(9, 5)


In [18]:
l=[1,2,3,4,5]
for idx,val in enumerate(l,5):
    print(idx,'-->',val)

5 --> 1
6 --> 2
7 --> 3
8 --> 4
9 --> 5


In [21]:
l=[i for i in range(1,101)]

def fn(val):
    return val%2==0
# for ele in filter(fn,l):
#     print(ele)
for ele in filter(lambda x:x%2!=0,l):
    print(ele)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


In [27]:
import math
l=[i for i in range(1,101)]
for ele in filter(lambda x:math.isqrt(x)**2==x,l):
    print(ele)


1
4
9
16
25
36
49
64
81
100


In [25]:
import math
math.sqrt(2)

1.4142135623730951

In [29]:
l=[i for i in range(1,101)]
for ele in filter(lambda x:int(x**0.5)==x**0.5,l):
    print(ele)

1
4
9
16
25
36
49
64
81
100


In [34]:
#map
l=[1,2,3,4,5,6,7,8,9,10]
for ele in map(lambda x:x**2,l):
    print(ele)


1
4
9
16
25
36
49
64
81
100


In [40]:
l=[1,2,3,4,5,6,7,8,9,10]
for ele in map(lambda x,y:x+y,l,range(101,201)):
    print(ele)

102
104
106
108
110
112
114
116
118
120


In [45]:
#reduce

from functools import reduce
l=[1,2,3,40,5,6]
reduce(lambda x,y:x+y,l[:3],100)
reduce(lambda a,b:max(a,b),l)

40

In [48]:
max(l)
min(l)
sum(l)

57

In [55]:
import random

random.shuffle(l)

l2=sorted(l)
print(l)
print(l2)

[1, 5, 2, 40, 3, 6]
[1, 2, 3, 5, 6, 40]


In [57]:
l=[(10,20),(20,10),(15,30),(30,25),(10,15)]
sorted(l,key=lambda x:x[1])




[(20, 10), (10, 15), (10, 20), (30, 25), (15, 30)]

In [60]:
class car:
    def __init__(self,model,speed,milage):
        self.model=model
        self.speed=speed
        self.milage=milage
    def __fn__(self):
        print(f"speed: {self.speed} model: {self.model} milage: {self.milage}") 


C1=car("A",300,20)
C2=car("B",250,50)
C3=car("C",200,45)
l=[C1,C2,C3]
for car in sorted(l,key=lambda x:x.speed):
    print(car.model)

C
B
A


In [63]:
import numpy as np
print(np.__version__)

l1=[1,2,3,4]
l2=[[1,2,3],[4,5,6]]
print(l2[1][2])
l3=[[[1,2,3],[4,5,6]], [[10,20,30],[40,50,60]], [[100,200,300],[400,500,600]]]
print(l3[1][0][1])

1.26.4
6
20


In [76]:
n1=np.array(l1)
print(n1, type(n1))
n2=np.array(l2)
print(n2)
n3=np.array(l3)
n1.shape
n3.shape
n2.ndim
n3[1,1,1]

[1 2 3 4] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


50

In [68]:
n2
l3[0][1][2]

6

In [81]:
n3=np.array(l3,dtype='float32')
n3.dtype
print(n3[0],type(n3[0,0,0]))

[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.float32'>


In [89]:
l=[[1,2,3],[10,20],'hello']
l
print(type(l))
n1=np.array(l,dtype='O')
print(n1)
n1

<class 'list'>
[list([1, 2, 3]) list([10, 20]) 'hello']


array([list([1, 2, 3]), list([10, 20]), 'hello'], dtype=object)

In [92]:
n1=np.arange(1,11,3,dtype='f4')
n1

array([ 1.,  4.,  7., 10.], dtype=float32)

In [94]:
n2=np.arange(1,101,4,dtype='f4')
n2

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41., 45., 49.,
       53., 57., 61., 65., 69., 73., 77., 81., 85., 89., 93., 97.],
      dtype=float32)

In [97]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [98]:
shape=[2,3,3]
np.ones(shape)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [101]:
shape=[4,5]
np.zeros(shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [113]:
np.random.rand(2,3)

array([[0.27418497, 0.67962534, 0.01354703],
       [0.11125094, 0.52606951, 0.55521074]])

In [114]:
np.random.random(size=(2,3))

array([[0.91282971, 0.24674064, 0.68673643],
       [0.12445914, 0.82550828, 0.10240361]])

In [123]:
np.random.randn(2,3)

array([[ 0.48479204, -0.66091787,  0.36852217],
       [ 0.7618844 ,  0.49845873, -0.17206622]])

In [125]:
np.random.randint(10,20,size=(2,3))

array([[13, 13, 19],
       [15, 10, 11]])

In [1]:
import numpy as np
a=np.array([-1,-3,5,6,7,0])
a[a<0]=0
print(a)

[0 0 5 6 7 0]


In [2]:
arr=np.array([[1,3],[-3,4],[5,6]])
arr

array([[ 1,  3],
       [-3,  4],
       [ 5,  6]])

In [3]:
arr[arr[:,0]>=0]

array([[1, 3],
       [5, 6]])

In [11]:
import pandas as pd
marks={
    'DBMS':[12,30,19,23,26],
    'OS':[26,28,11,23,19],
    'CN':[13,25,26,30,24]
}
df=pd.DataFrame(marks,index=['A','B','C','D','E'],columns=['DBMS','OS'])
df

DBMS  OS
A    12  26
B    30  28
C    19  11
D    23  23
E    26  19

In [13]:
na=np.random.randint(50,100,(10,3))
na

array([[97, 64, 80],
       [81, 53, 94],
       [91, 58, 53],
       [99, 78, 60],
       [69, 91, 55],
       [92, 60, 83],
       [65, 80, 88],
       [97, 60, 95],
       [78, 56, 50],
       [87, 60, 71]])

In [17]:
df=pd.DataFrame(na,columns=['DBMS','OS','CN'],index=[i for i in range(1,11)])
df

DBMS  OS  CN
1     97  64  80
2     81  53  94
3     91  58  53
4     99  78  60
5     69  91  55
6     92  60  83
7     65  80  88
8     97  60  95
9     78  56  50
10    87  60  71

In [18]:
df.tail()

DBMS  OS  CN
6     92  60  83
7     65  80  88
8     97  60  95
9     78  56  50
10    87  60  71

In [19]:
df.head(4)

DBMS  OS  CN
1    97  64  80
2    81  53  94
3    91  58  53
4    99  78  60

In [20]:
df.to_csv("Marks.csv",sep='|',index=False)

In [21]:
ndf=pd.read_csv("Marks.csv",sep='|')
ndf

DBMS  OS  CN
0    97  64  80
1    81  53  94
2    91  58  53
3    99  78  60
4    69  91  55
5    92  60  83
6    65  80  88
7    97  60  95
8    78  56  50
9    87  60  71

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DBMS    10 non-null     int32
 1   OS      10 non-null     int32
 2   CN      10 non-null     int32
dtypes: int32(3)
memory usage: 200.0 bytes


In [25]:
# df.drop(columns=['DBMS'])
df.drop(index=[1,2])

DBMS  OS  CN
3     91  58  53
4     99  78  60
5     69  91  55
6     92  60  83
7     65  80  88
8     97  60  95
9     78  56  50
10    87  60  71

In [26]:
df['CN']

1     80
2     94
3     53
4     60
5     55
6     83
7     88
8     95
9     50
10    71
Name: CN, dtype: int32

In [29]:
df[['DBMS','CN']]

DBMS  CN
1     97  80
2     81  94
3     91  53
4     99  60
5     69  55
6     92  83
7     65  88
8     97  95
9     78  50
10    87  71

In [ ]:
df.iloc

In [30]:
ndf=df[df['DBMS'] >= 20]
ndf=ndf[ndf['CN']>=20]
ndf

DBMS  OS  CN
1     97  64  80
2     81  53  94
3     91  58  53
4     99  78  60
5     69  91  55
6     92  60  83
7     65  80  88
8     97  60  95
9     78  56  50
10    87  60  71

In [35]:
data=pd.read_csv("weather_data_cities.csv")

In [39]:
res=data.groupby('event')['windspeed'].mean()
res

event
Rain     5.0
Snow     4.5
Sunny    4.5
Name: windspeed, dtype: float64

In [41]:
data.pivot(columns='temperature', index='event')

ValueError: Index contains duplicate entries, cannot reshape