In [3]:
all([1,2,3,4,5,0])

False

In [6]:
any([0,0,0])

False

In [7]:
dir(int)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [9]:
divmod(20,3)

(6, 2)

In [13]:
l=[10,20,30,40]

for idx,val  in enumerate(l,6):
    print(idx,"-->",val)

6 --> 10
7 --> 20
8 --> 30
9 --> 40


In [ ]:

l=[i for i in  range(1,101)]
def fn(x):
    return x%2==0
for ele in filter(fn,l):
    print(ele)

In [23]:
import math
l=[i for i in range(1,101)]
def fn(x):
    return math.isqrt(x)**2==x

for ele in filter(fn,l):
    print(ele)

1
4
9
16
25
36
49
64
81
100


In [ ]:
for ele in map(lambda x:x**2,l):
    print(ele)

In [25]:
for ele in map(lambda x:x-20,l):
    print(ele)

-19
-18
-17
-16
-15
-14
-13
-12
-11
-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80


In [31]:
from functools import reduce
reduce(lambda x,y:max(x,y),l[:5] , 1)

5

In [ ]:
import random
random.shuffle(l)
print(l)
sorted(l)  #return a new list

[90, 19, 16, 7, 8, 14, 66, 10, 36, 77, 30, 61, 49, 9, 46, 67, 98, 99, 22, 88, 72, 100, 29, 26, 97, 56, 13, 35, 81, 69, 89, 83, 50, 37, 53, 18, 93, 27, 84, 4, 1, 45, 39, 6, 59, 42, 3, 11, 5, 28, 40, 70, 65, 17, 33, 68, 82, 73, 80, 54, 63, 47, 85, 57, 78, 55, 31, 20, 58, 64, 21, 74, 2, 96, 86, 44, 23, 91, 51, 60, 15, 76, 71, 24, 43, 87, 38, 52, 62, 48, 25, 95, 79, 75, 32, 12, 41, 34, 92, 94]


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [37]:
l=[(10,20),(20,10),(15,30),(30,25),(10,15)]
sorted(l,key=lambda x:x[1])

[(20, 10), (10, 15), (10, 20), (30, 25), (15, 30)]

In [ ]:
class Car:
    def __init__(self,model,speed,milage):
        self.model=model
        self.speed=speed
        self.milage=milage
    def __repr__(self):
        return f"model={self.model}, speed={self.speed}, milage={self.milage})"
        
        
C1=Car("A",100,30)
C2=Car("B",200,40)
C3=Car("C",80,36)
l=[C1,C2,C3]


sorted_cars=sorted(l,key=lambda car:car.speed)
print(sorted_cars)        

[model=A, speed=100, milage=30), model=B, speed=200, milage=40), model=C, speed=80, milage=36)]
[model=C, speed=80, milage=36), model=A, speed=100, milage=30), model=B, speed=200, milage=40)]


In [45]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [50]:
arr=np.array([[1,2,3],[4,5,6]])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(np.__version__)

2
(2, 3)
6
int32
1.26.4


In [ ]:
#Internal code written i c or C++ thats why it is fast


In [51]:
l=[[1,2,3],[4,5,6]]
print(l[1][2])

6


In [ ]:
l3=[[[1,2,3],[4,5,6]], [[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]]
print(l3[2][1][2])


600


NameError: name 'n3' is not defined

In [63]:
l=[1,2,2,'Hello']
a=np.array(l,dtype='O')
a

array([1, 2, 2, 'Hello'], dtype=object)

In [64]:
np.linspace(1,3,7)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        ])